'use client'
import { Providers } from "../providers";
import Navbar from "@/dashboardComponents/Navbar";
import Footer from "@/dashboardComponents/Footer";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
        <body>
          <Providers>
            <Navbar />
            {children}
            <Footer />
          </Providers>
        </body>
      </html>
  )
}
